# Generated by Django 3.2.23 on 2024-04-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='enquiry_type',
            field=models.CharField(choices=[('PRODUCT_QUERY', 'Product Query'), ('ORDER_QUERY', 'Order Query'), ('OTHER', 'Other')], default='DS', max_length=254),
        ),
    ]
