# Generated by Django 3.2.23 on 2024-04-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_outfit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outfit',
        ),
    ]
